= Twiliofaces
Fiorenzo Pizza<fiorenzo.pizza@gmail.com>
:imagesdir: assets
:homepage: http://twiliofaces.org

http://twiliofaces.org[Twiliofaces] Come usare Twilio nelle tue applicazione java ee!

Da poco meno di un anno anche un italia è sbarcata Twilio<http://twilio.com>, compagnia americana che offre servizi telefonici in cloud 
tramite l'uso di semplici api. La semplicita d'uso delle sue api coinsente agevolmente di gestire servizi vocali e 
di messaggistica direttamente integrabili in applicazioni pre-esistenti.
Non serve avere server voip dedicato, basta avere un indirizzo pubblico raggiungibile dai
server twilio, crerare un account e iniziare a sperimentare.
L'account gratuito consente di scegliere un numero telefonico della numerazione italiana, permette
di abilitare un numero pre-esistente per testare l'interazione coi servizi twilio.
Le api per utilizzare i servizi twilio, scariucabili gratuitamente da 
github[http://github.com/twilio], sono manutenute dalla societa' e coprono i principali linguaggi di programmazione 
tra cui java.

Cosa vedrete in questo articolo
- Come usate le api java twilio
- Come usare twiliofaces
- Come verificare il vs twiml
- Come contribuire al progetto twiliofaces

toc::[]

== Creaimo un progetto maven ed includiamo twilio-sdk

Scaricato l'sdk ufficiale iniziamo a guardare gli esempi.

== Aggiungiamo twiliofaces nel pom.xml

Vediamo *come cambia la musica*

== Come generare twiml usando tag jsf

Tutto parte da qui: se in jsf si produce xhtml usando facelets e tag jsf, perche' non fare la stessa cosa con twilio?

== Come creare jsf Controller con @TwilioScope

Un controller in jsf/cdi ha un ciclo di vita che spazia dalla request/sessione/applicazione. Nel caso di twilio e' 
comodo avere dei controller che vivono perl'intera telefonata.
ogni telefoanata ha un suo CallSid (identificativo unico di chiamata) e alla fine di ogni chiamata twilio ci notifica
tutte le infomazioni su un link callback link.

== Cosa manca a twiliofaces

manca il twilio client javascript in tag jsf e api piu fluenti sia per sms che per effettuare le chiamate.

